// Generated by gencpp from file imu_gnss/gps_ins_msg.msg
// DO NOT EDIT!


#ifndef IMU_GNSS_MESSAGE_GPS_INS_MSG_H
#define IMU_GNSS_MESSAGE_GPS_INS_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <nav_msgs/Odometry.h>

namespace imu_gnss
{
template <class ContainerAllocator>
struct gps_ins_msg_
{
  typedef gps_ins_msg_<ContainerAllocator> Type;

  gps_ins_msg_()
    : header()
    , odom()
    , gnss_status(0)  {
    }
  gps_ins_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , odom(_alloc)
    , gnss_status(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::nav_msgs::Odometry_<ContainerAllocator>  _odom_type;
  _odom_type odom;

   typedef int32_t _gnss_status_type;
  _gnss_status_type gnss_status;





  typedef boost::shared_ptr< ::imu_gnss::gps_ins_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::imu_gnss::gps_ins_msg_<ContainerAllocator> const> ConstPtr;

}; // struct gps_ins_msg_

typedef ::imu_gnss::gps_ins_msg_<std::allocator<void> > gps_ins_msg;

typedef boost::shared_ptr< ::imu_gnss::gps_ins_msg > gps_ins_msgPtr;
typedef boost::shared_ptr< ::imu_gnss::gps_ins_msg const> gps_ins_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::imu_gnss::gps_ins_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::imu_gnss::gps_ins_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::imu_gnss::gps_ins_msg_<ContainerAllocator1> & lhs, const ::imu_gnss::gps_ins_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.odom == rhs.odom &&
    lhs.gnss_status == rhs.gnss_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::imu_gnss::gps_ins_msg_<ContainerAllocator1> & lhs, const ::imu_gnss::gps_ins_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace imu_gnss

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::imu_gnss::gps_ins_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::imu_gnss::gps_ins_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_gnss::gps_ins_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::imu_gnss::gps_ins_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_gnss::gps_ins_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::imu_gnss::gps_ins_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::imu_gnss::gps_ins_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b2ee0d9b0bb16ef76cad998d234b5f6";
  }

  static const char* value(const ::imu_gnss::gps_ins_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b2ee0d9b0bb16efULL;
  static const uint64_t static_value2 = 0x76cad998d234b5f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::imu_gnss::gps_ins_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "imu_gnss/gps_ins_msg";
  }

  static const char* value(const ::imu_gnss::gps_ins_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::imu_gnss::gps_ins_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"nav_msgs/Odometry odom\n"
"int32 gnss_status\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: nav_msgs/Odometry\n"
"# This represents an estimate of a position and velocity in free space.  \n"
"# The pose in this message should be specified in the coordinate frame given by header.frame_id.\n"
"# The twist in this message should be specified in the coordinate frame given by the child_frame_id\n"
"Header header\n"
"string child_frame_id\n"
"geometry_msgs/PoseWithCovariance pose\n"
"geometry_msgs/TwistWithCovariance twist\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseWithCovariance\n"
"# This represents a pose in free space with uncertainty.\n"
"\n"
"Pose pose\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/TwistWithCovariance\n"
"# This expresses velocity in free space with uncertainty.\n"
"\n"
"Twist twist\n"
"\n"
"# Row-major representation of the 6x6 covariance matrix\n"
"# The orientation parameters use a fixed-axis representation.\n"
"# In order, the parameters are:\n"
"# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n"
"float64[36] covariance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Twist\n"
"# This expresses velocity in free space broken into its linear and angular parts.\n"
"Vector3  linear\n"
"Vector3  angular\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Vector3\n"
"# This represents a vector in free space. \n"
"# It is only meant to represent a direction. Therefore, it does not\n"
"# make sense to apply a translation to it (e.g., when applying a \n"
"# generic rigid transformation to a Vector3, tf2 will only apply the\n"
"# rotation). If you want your data to be translatable too, use the\n"
"# geometry_msgs/Point message instead.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::imu_gnss::gps_ins_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::imu_gnss::gps_ins_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.odom);
      stream.next(m.gnss_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gps_ins_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::imu_gnss::gps_ins_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::imu_gnss::gps_ins_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "odom: ";
    s << std::endl;
    Printer< ::nav_msgs::Odometry_<ContainerAllocator> >::stream(s, indent + "  ", v.odom);
    s << indent << "gnss_status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gnss_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IMU_GNSS_MESSAGE_GPS_INS_MSG_H
