// Generated by gencpp from file Base_control/ControlCmd.msg
// DO NOT EDIT!


#ifndef BASE_CONTROL_MESSAGE_CONTROLCMD_H
#define BASE_CONTROL_MESSAGE_CONTROLCMD_H

#include <ros/service_traits.h>


#include <Base_control/ControlCmdRequest.h>
#include <Base_control/ControlCmdResponse.h>


namespace Base_control
{

struct ControlCmd
{

typedef ControlCmdRequest Request;
typedef ControlCmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ControlCmd
} // namespace Base_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::Base_control::ControlCmd > {
  static const char* value()
  {
    return "c3b695435bdb417bcaf4f8d54b0b457e";
  }

  static const char* value(const ::Base_control::ControlCmd&) { return value(); }
};

template<>
struct DataType< ::Base_control::ControlCmd > {
  static const char* value()
  {
    return "Base_control/ControlCmd";
  }

  static const char* value(const ::Base_control::ControlCmd&) { return value(); }
};


// service_traits::MD5Sum< ::Base_control::ControlCmdRequest> should match 
// service_traits::MD5Sum< ::Base_control::ControlCmd > 
template<>
struct MD5Sum< ::Base_control::ControlCmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::Base_control::ControlCmd >::value();
  }
  static const char* value(const ::Base_control::ControlCmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::Base_control::ControlCmdRequest> should match 
// service_traits::DataType< ::Base_control::ControlCmd > 
template<>
struct DataType< ::Base_control::ControlCmdRequest>
{
  static const char* value()
  {
    return DataType< ::Base_control::ControlCmd >::value();
  }
  static const char* value(const ::Base_control::ControlCmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::Base_control::ControlCmdResponse> should match 
// service_traits::MD5Sum< ::Base_control::ControlCmd > 
template<>
struct MD5Sum< ::Base_control::ControlCmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::Base_control::ControlCmd >::value();
  }
  static const char* value(const ::Base_control::ControlCmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::Base_control::ControlCmdResponse> should match 
// service_traits::DataType< ::Base_control::ControlCmd > 
template<>
struct DataType< ::Base_control::ControlCmdResponse>
{
  static const char* value()
  {
    return DataType< ::Base_control::ControlCmd >::value();
  }
  static const char* value(const ::Base_control::ControlCmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASE_CONTROL_MESSAGE_CONTROLCMD_H
