// Generated by gencpp from file Base_control/ControlCmdResponse.msg
// DO NOT EDIT!


#ifndef BASE_CONTROL_MESSAGE_CONTROLCMDRESPONSE_H
#define BASE_CONTROL_MESSAGE_CONTROLCMDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace Base_control
{
template <class ContainerAllocator>
struct ControlCmdResponse_
{
  typedef ControlCmdResponse_<ContainerAllocator> Type;

  ControlCmdResponse_()
    : zz(0.0)  {
    }
  ControlCmdResponse_(const ContainerAllocator& _alloc)
    : zz(0.0)  {
  (void)_alloc;
    }



   typedef float _zz_type;
  _zz_type zz;





  typedef boost::shared_ptr< ::Base_control::ControlCmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::Base_control::ControlCmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ControlCmdResponse_

typedef ::Base_control::ControlCmdResponse_<std::allocator<void> > ControlCmdResponse;

typedef boost::shared_ptr< ::Base_control::ControlCmdResponse > ControlCmdResponsePtr;
typedef boost::shared_ptr< ::Base_control::ControlCmdResponse const> ControlCmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::Base_control::ControlCmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::Base_control::ControlCmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace Base_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'Base_control': ['/home/qh/robot_ws/src/Base_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::Base_control::ControlCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::Base_control::ControlCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Base_control::ControlCmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::Base_control::ControlCmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Base_control::ControlCmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::Base_control::ControlCmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::Base_control::ControlCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5c143908f173ddc20925bd9da1bb3228";
  }

  static const char* value(const ::Base_control::ControlCmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5c143908f173ddc2ULL;
  static const uint64_t static_value2 = 0x0925bd9da1bb3228ULL;
};

template<class ContainerAllocator>
struct DataType< ::Base_control::ControlCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Base_control/ControlCmdResponse";
  }

  static const char* value(const ::Base_control::ControlCmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::Base_control::ControlCmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 zz\n\
\n\
";
  }

  static const char* value(const ::Base_control::ControlCmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::Base_control::ControlCmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.zz);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlCmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::Base_control::ControlCmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::Base_control::ControlCmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "zz: ";
    Printer<float>::stream(s, indent + "  ", v.zz);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASE_CONTROL_MESSAGE_CONTROLCMDRESPONSE_H
